title: Johannes Herforth's Homepage # name of the site
author: Johannes Herforth # name of site's author
email: hello@herforth.xyz # email of site's author
url: https://herforth.xyz # root address of the site
baseurl: "" # "/no-style-please" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  I'm a computer scientist born in Germany and raised in Luxembourg. I
  strive to keep my work simple to have more time to explore and enjoy life.

permalink: /:slug.html

favicon: "favi.jpg" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar


scholar:
  style: apa
  bibliography_list_tag: ul
  sort_by: year,month
  order: descending
  bibliography_template: bib


reference_names:
  - "Herforth, J. G."
  - "Herforth, J."
